logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS
  level:
    com.itheima: debug


spring:
  rabbitmq:
    host: 192.168.47.100
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        multiplier: 2
    publisher-confirm-type: correlated
    publisher-returns: true
